name: 'AlphaVantageDataTransformation'
version: '1.0.0'
config-version: 2

profile: 'AlphaVantageDataTransformation'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  AlphaVantageDataTransformation:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: view
      +schema: INTERMEDIATE
    marts:
      +materialized: table
      +schema: MARTS
      +data_tests:
        unique:
          +severity: error
        not_null:
          +severity: error